# This is a sample config.toml for use with Supabase CLI
# Actual values would be populated during project setup

# Project configuration
[project]
# The ID of your Supabase project (found in the Supabase dashboard URL)
id = "your-project-ref" 

# Local development configuration
[local]
api_port = 54321
db_port = 54322
studio_port = 54323

# Authentication configuration
[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
autoconfirm = false

# Email authentication configuration
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true 