# This is a config.toml for use with Supabase CLI

# Project configuration
project_id = "yimvluqgmullzscldfyw"

# Local development configuration


# Authentication configuration
[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]


# Email authentication configuration
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true 