export const AcsCodes = [
  {
    id: 'IH.I.A.K1',
    description: 'Certification requirements, recency of experience, and recordkeeping.',
    area: 'Preflight Preparation',
    task: 'Pilot Qualifications',
    subTask: 'Certification/Recency',
    knowledge: 'Regulations',
    examType: 'IRH',
  },
  {
    id: 'IH.I.A.K2',
    description: 'Privileges and limitations.',
    area: 'Preflight Preparation',
    task: 'Pilot Qualifications',
    subTask: 'Privileges/Limitations',
    knowledge: 'Regulations',
    examType: 'IRH',
  },
  {
    id: 'IH.I.A.K3',
    description: 'Part 68 BasicMed privileges and limitations.',
    area: 'Preflight Preparation',
    task: 'Pilot Qualifications',
    subTask: 'BasicMed',
    knowledge: 'Regulations',
    examType: 'IRH',
  },
  {
    id: 'IH.I.A.R1',
    description: 'Proficiency versus currency.',
    area: 'Preflight Preparation',
    task: 'Pilot Qualifications',
    subTask: 'Proficiency vs Currency',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.A.R2',
    description: 'Personal minimums.',
    area: 'Preflight Preparation',
    task: 'Pilot Qualifications',
    subTask: 'Personal Minimums',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.A.R3',
    description:
      "Fitness for flight and physiological factors that might affect the pilot's ability to fly under instrument conditions.",
    area: 'Preflight Preparation',
    task: 'Pilot Qualifications',
    subTask: 'Fitness for Flight',
    knowledge: 'Aeromedical',
    examType: 'IRH',
  },
  {
    id: 'IH.I.A.R4',
    description:
      'Flying unfamiliar helicopters or operating with unfamiliar flight display systems and avionics.',
    area: 'Preflight Preparation',
    task: 'Pilot Qualifications',
    subTask: 'Unfamiliar Equipment',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.A.S1',
    description:
      'Apply requirements to act as pilot-in-command (PIC) under Instrument Flight Rules (IFR) in a scenario given by the evaluator.',
    area: 'Preflight Preparation',
    task: 'Pilot Qualifications',
    subTask: 'Apply PIC Requirements',
    knowledge: 'Regulations',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K1',
    description:
      'Sources of weather data (e.g., National Weather Service, Flight Service) for flight planning purposes.',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Weather Data Sources',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K2',
    description:
      'Acceptable weather products and resources required for preflight planning, current and forecast weather for departure, en route, and arrival phases of flight such as:',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Weather Products/Resources',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K2a',
    description: 'a. Airport Observations (METAR and SPECI) and Pilot Observations (PIREP)',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'METAR/SPECI/PIREP',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K2b',
    description: 'b. Surface Analysis Chart, Ceiling and Visibility Chart (CVA)',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Surface/CVA Charts',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K2c',
    description: 'c. Terminal Aerodrome Forecasts (TAF)',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'TAF',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K2d',
    description: 'd. Graphical Forecasts for Aviation (GFA)',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'GFA',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K2e',
    description: 'e. Wind and Temperature Aloft Forecast (FB)',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Winds Aloft (FB)',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K2f',
    description: 'f. Convective Outlook (AC)',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Convective Outlook',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K2g',
    description:
      "g. Inflight Aviation Weather Advisories including Airmen's Meteorological Information (AIRMET), Significant Meteorological Information (SIGMET), and Convective SIGMET",
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Inflight Advisories',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3',
    description:
      'Meteorology applicable to the departure, en route, alternate, and destination for flights conducted under Instrument Flight Rules (IFR) to include expected climate and hazardous conditions such as:',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Applied Meteorology',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3a',
    description: 'a. Atmospheric composition and stability',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Stability',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3b',
    description: 'b. Wind (e.g., windshear, mountain wave, factors affecting wind, etc.)',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Wind/Windshear',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3c',
    description: 'c. Temperature and heat exchange',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Temperature/Heat',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3d',
    description: 'd. Moisture/precipitation',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Moisture/Precipitation',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3e',
    description: 'e. Weather system formation, including air masses and fronts',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Weather Systems/Fronts',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3f',
    description: 'f. Clouds',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Clouds',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3g',
    description: 'g. Turbulence',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Turbulence',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3h',
    description: 'h. Thunderstorms and microbursts',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Thunderstorms/Microbursts',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3i',
    description: 'i. Icing and freezing level information',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Icing/Freezing Level',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3j',
    description: 'j. Fog/mist',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Fog/Mist',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3k',
    description: 'k. Frost',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Frost',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K3l',
    description: 'l. Obstructions to visibility (e.g., smoke, haze, volcanic ash, etc.)',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Visibility Obstructions',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.K4',
    description: 'Flight deck instrument displays of digital weather and aeronautical information.',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Digital Weather Displays',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.R1',
    description: 'Making the go/no-go and continue/divert decisions, including:',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Go/No-Go Decisions',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.R1a',
    description: 'a. Circumstances that would make diversion prudent',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Diversion Decisions',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.R1b',
    description: 'b. Personal weather minimums',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Personal Minimums',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.R1c',
    description:
      'c. Hazardous weather conditions, including known or forecast icing or turbulence aloft',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Hazardous Weather Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.R2',
    description: 'Use and limitations of:',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Weather Equipment Use',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.R2a',
    description: 'a. Installed onboard weather equipment',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Onboard Weather Equip Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.R2b',
    description: 'b. Aviation weather reports and forecasts',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Weather Report Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.R2c',
    description: 'c. Inflight weather resources',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Inflight Weather Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.S1',
    description: 'Use available aviation weather resources to obtain an adequate weather briefing.',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Obtain Weather Briefing',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.S2',
    description:
      'Analyze the implications of at least three of the conditions listed in K3a through K3l, using actual weather or weather conditions provided by the evaluator.',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Analyze Weather Conditions',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.S3',
    description: 'Correlate weather information to make a go/no-go decision.',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Correlate Weather/Go-No-Go',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.B.S4',
    description:
      'Determine whether an alternate airport is required, and, if required, whether the selected alternate airport meets regulatory requirements.',
    area: 'Preflight Preparation',
    task: 'Weather Information',
    subTask: 'Alternate Airport Req',
    knowledge: 'Regulations',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K1',
    description: 'Route planning, including consideration of:',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Route Planning Factors',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K1a',
    description: 'a. Available navigational facilities',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Nav Facilities',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K1b',
    description: 'b. Special use airspace',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Special Use Airspace',
    knowledge: 'Airspace',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K1c',
    description: 'c. Preferred routes',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Preferred Routes',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K1d',
    description: 'd. Primary and alternate airports',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Primary/Alternate Airports',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K1e',
    description: 'e. Enroute charts',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Enroute Charts',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K1f',
    description: 'f. Chart Supplements',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Chart Supplements',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K1g',
    description: 'g. NOTAMs',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'NOTAMs',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K1h',
    description: 'h. Terminal Procedures Publications (TPP)',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'TPP',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K2',
    description:
      'Altitude selection accounting for terrain and obstacles, IFR cruising altitudes, and effect of wind and oxygen requirements.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Altitude Selection',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K3',
    description: 'Calculating:',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Flight Plan Calculations',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K3a',
    description:
      'a. Time, climb and descent rates, course, distance, heading, true airspeed, and groundspeed',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Performance Calculations',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K3b',
    description:
      'b. Estimated time of arrival, including conversion to universal coordinated time (UTC)',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'ETA/UTC Calculation',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K3c',
    description: 'c. Fuel requirements, including reserve',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Fuel Calculation',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K4',
    description: 'Elements of an IFR flight plan.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'IFR Flight Plan Elements',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.K5',
    description:
      'Procedures for activating and closing an IFR flight plan in controlled and uncontrolled airspace.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Activate/Close IFR Plan',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.R1',
    description: 'Pilot.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Pilot Risk Factors',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.R2',
    description: 'Helicopter.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Helicopter Risk Factors',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.R3',
    description:
      'Environment (e.g., weather, icing, airports/heliports/helipads/landing areas, airspace, terrain, obstacles).',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Environmental Risk Factors',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.R4',
    description: 'External pressures.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'External Pressures Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.R5',
    description: 'Limitations of air traffic control (ATC) services.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'ATC Service Limitations Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.R6',
    description: 'Limitations of electronic planning applications and programs.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Electronic Planning Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.R7',
    description: 'Fuel planning.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Fuel Planning Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.S1',
    description:
      'Prepare, present, and explain a cross-country flight plan assigned by the evaluator including a risk analysis based on real time weather, which includes calculating time en route and fuel considering factors such as power settings, operating altitude, wind, fuel reserve requirements, and weight and balance requirements.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Prepare/Explain XC Plan',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.S2',
    description: 'Recalculate fuel reserves based on a scenario provided by the evaluator.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Recalculate Fuel Reserves',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.S3',
    description: 'Create a navigation plan and simulate filing an IFR flight plan.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Create Nav Plan/File IFR',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.S4',
    description:
      'Interpret departure, arrival, en route, and approach procedures with reference to appropriate and current charts.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Interpret Charts/Procedures',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.S5',
    description:
      'Recognize contamination due to rotor or airframe icing and demonstrate knowledge of the adverse effects of icing during pre-takeoff, takeoff, cruise, and landing phases of flight as well as the corrective actions.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Icing Recognition/Effects',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.I.C.S6',
    description:
      'Apply pertinent information from appropriate and current aeronautical charts, Chart Supplements; Notices to Air Missions (NOTAMs) relative to airport, runway and taxiway closures; and other flight publications.',
    area: 'Preflight Preparation',
    task: 'Cross-Country Flight Planning',
    subTask: 'Apply Chart/Publication Info',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.II.A.K1',
    description:
      'The general operational characteristics and limitations of applicable anti-icing and deicing systems, including airframe, rotor, intake, fuel, and pitot-static systems.',
    area: 'Preflight Procedures',
    task: 'Aircraft Systems Related to Instrument Flight Rules (IFR) Operations',
    subTask: 'Anti-ice/Deice Systems',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.II.A.K2',
    description: 'Flight control systems.',
    area: 'Preflight Procedures',
    task: 'Aircraft Systems Related to Instrument Flight Rules (IFR) Operations',
    subTask: 'Flight Control Systems',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.II.A.R1',
    description: 'Operations in icing conditions.',
    area: 'Preflight Procedures',
    task: 'Aircraft Systems Related to Instrument Flight Rules (IFR) Operations',
    subTask: 'Icing Operations Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IL.A.R2',
    description: 'Limitations of anti-icing and deicing systems.',
    area: 'Preflight Procedures',
    task: 'Aircraft Systems Related to Instrument Flight Rules (IFR) Operations',
    subTask: 'Anti-ice/Deice Limits Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.II.A.R3',
    description: 'Use of automated systems in instrument conditions.',
    area: 'Preflight Procedures',
    task: 'Aircraft Systems Related to Instrument Flight Rules (IFR) Operations',
    subTask: 'Automation Use Risk (IMC)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.II.A.S1',
    description:
      'Demonstrate familiarity with anti-icing or deicing procedures or information published by the manufacturer specific to the helicopter used on the practical test.',
    area: 'Preflight Procedures',
    task: 'Aircraft Systems Related to Instrument Flight Rules (IFR) Operations',
    subTask: 'Demonstrate Anti-ice/Deice Use',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.II.A.S2',
    description:
      'Demonstrate familiarity with the automatic flight control system (AFCS) procedures or information published by the manufacturer specific to the aircraft used on the practical test, if applicable.',
    area: 'Preflight Procedures',
    task: 'Aircraft Systems Related to Instrument Flight Rules (IFR) Operations',
    subTask: 'Demonstrate AFCS Use',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.K1',
    description: "Operation of the helicopter's applicable flight instrument system(s), including.",
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Flight Instrument Ops',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.K1a',
    description: 'a. Pitot-static instrument system and associated instruments',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Pitot-Static System',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.K1b',
    description: 'b. Gyroscopic/electric instrument system and associated instruments',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Gyroscopic/Electric Instruments',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.K1c',
    description:
      'c. Electrical systems, electronic flight instrument displays [primary flight display (PFD), multi-function display (MFD)], transponder and automatic dependent surveillance - broadcast (ADS-B)',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Electrical/Displays/XPDR/ADS-B',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.K1d',
    description: 'd. Magnetic compass',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Magnetic Compass',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.K2',
    description: "Operation of the helicopter's applicable navigation system(s), including:",
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Navigation System Ops',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.K2a',
    description:
      'a. Very high frequency (VHF) Omnidirectional Range (VOR), distance measuring equipment (DME), instrument landing system (ILS), marker beacon receiver/indicators',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'VOR/DME/ILS/Marker Beacon',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.K2b',
    description:
      'b. Area navigation (RNAV), global positioning system (GPS), Wide Area Augmentation System (WAAS), flight management system (FMS), autopilot',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'RNAV/GPS/WAAS/FMS/AP',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.K3',
    description: 'Use of an electronic flight bag (EFB), if used.',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'EFB Use',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.R1',
    description: 'Monitoring and management of automated systems.',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Automation Mgmt Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.R2',
    description: 'Difference between approved and non-approved navigation devices.',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Approved Nav Devices Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.R3',
    description: 'Modes of flight and navigation instruments, including failure conditions.',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Instrument Modes/Failure Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.R4',
    description: 'Use of an electronic flight bag.',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'EFB Use Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.R5',
    description: 'Use of navigation databases.',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Nav Database Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.S1',
    description: 'Operate and manage installed instruments and navigation equipment.',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Operate Instruments/Nav Equip',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.II.B.S2',
    description: 'Operate and manage an applicant supplied electronic flight bag (EFB), if used.',
    area: 'Preflight Procedures',
    task: 'Helicopter Flight Instruments and Navigation Equipment',
    subTask: 'Operate EFB',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.II.C.K1',
    description:
      'Purpose of performing an instrument flight deck check and how to detect possible defects.',
    area: 'Preflight Procedures',
    task: 'Instrument Flight Deck Check',
    subTask: 'Inst Flight Deck Check Purpose',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.II.C.K2',
    description:
      'IFR airworthiness, including helicopter inspection requirements and required equipment for IFR flight.',
    area: 'Preflight Procedures',
    task: 'Instrument Flight Deck Check',
    subTask: 'IFR Airworthiness/Equip',
    knowledge: 'Regulations',
    examType: 'IRH',
  },
  {
    id: 'IH.II.C.K3',
    description:
      'Required procedures, documentation, and limitations of flying with inoperative equipment.',
    area: 'Preflight Procedures',
    task: 'Instrument Flight Deck Check',
    subTask: 'Inoperative Equipment Proc',
    knowledge: 'Regulations',
    examType: 'IRH',
  },
  {
    id: 'IH.II.C.R1',
    description: 'Operating with inoperative equipment.',
    area: 'Preflight Procedures',
    task: 'Instrument Flight Deck Check',
    subTask: 'Inop Equip Ops Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.II.C.R2',
    description: 'Operating with outdated navigation publications or databases.',
    area: 'Preflight Procedures',
    task: 'Instrument Flight Deck Check',
    subTask: 'Outdated Data Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.II.C.S1',
    description:
      'Perform preflight inspection by following the checklist appropriate to the helicopter and determine if the helicopter is in a condition for safe instrument flight.',
    area: 'Preflight Procedures',
    task: 'Instrument Flight Deck Check',
    subTask: 'Perform Preflight Check',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.K1',
    description:
      'Elements and procedures related to ATC clearances and pilot/controller responsibilities for departure, en route, and arrival phases of flight, including clearance void times.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'ATC Clearances/Responsibilities',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.K2',
    description: 'Pilot-in-Command (PIC) emergency authority.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'PIC Emergency Authority',
    knowledge: 'Regulations',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.K3',
    description:
      'Lost communication procedures and procedures for flights outside of radar environments.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Lost Comms/Non-Radar Proc',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.R1',
    description: 'Less than full understanding of an ATC clearance.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Misunderstanding ATC Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.R2',
    description: 'Inappropriate, incomplete, or incorrect ATC clearances.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Incorrect ATC Clearance Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.R3',
    description: 'ATC clearance inconsistent with helicopter performance or navigation capability.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Inconsistent ATC Clearance Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.R4',
    description: 'ATC clearance intended for other aircraft with similar call signs.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Similar Call Sign Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.S1',
    description:
      'Correctly copy, read back, interpret, and comply with simulated or actual ATC clearances in a timely manner using standard phraseology as provided in the Aeronautical Information Manual (AIM).',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Copy/Comply ATC Clearances',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.S2',
    description:
      'Correctly set communication frequencies, navigation systems (identifying when appropriate), and transponder codes in compliance with the ATC clearance.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Set Freq/Nav/XPDR Codes',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.S3',
    description: 'Use the current and appropriate paper or electronic navigation publications.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Use Current Nav Pubs',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.S4',
    description:
      'Intercept all courses, radials, and bearings appropriate to the procedure, route, or clearance in a timely manner.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Intercept Courses/Radials',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.S5',
    description:
      'Maintain the applicable airspeed ±10 knots, headings ±10°, altitude ±100 feet; track a course, radial, or bearing within ¾-scale deflection of the course deviation indicator (CDI).',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Maintain Flight Parameters (IMC)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.S6',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Apply SRM/CRM',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.A.S7',
    description: 'Perform the appropriate checklist items relative to the phase of flight.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Compliance with Air Traffic Control Clearances',
    subTask: 'Perform Checklists',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.K1',
    description:
      'Elements related to holding procedures, including reporting criteria, appropriate speeds, and recommended entry procedures for standard, nonstandard, published, and non-published holding patterns.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Holding Procedures Elements',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.R1',
    description:
      'Recalculating fuel reserves if assigned an unanticipated expect further clearance (EFC) time.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'EFC/Fuel Recalculation Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.R2',
    description:
      'Scenarios and circumstances that could result in minimum fuel or the need to declare an emergency.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Minimum Fuel Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.R3',
    description:
      'Scenarios that could lead to holding, including deteriorating weather at the planned destination.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Holding Scenario Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.R4',
    description: 'Holding entry and wind correction while holding.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Holding Entry/Wind Corr Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.S1',
    description:
      'Use an entry procedure appropriate for a standard, nonstandard, published, or non-published holding pattern.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Perform Holding Entry',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.S2',
    description:
      'Change to the holding airspeed appropriate for the altitude when 3 minutes or less from, but prior to arriving at, the holding fix and set appropriate power as needed for fuel conservation.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Adjust Holding Airspeed/Power',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.S3',
    description:
      'Recognize arrival at the holding fix and promptly initiate entry into the holding pattern.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Recognize Fix/Initiate Hold',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.S4',
    description:
      'Maintain airspeed ±10 knots, altitude ±100 feet, selected headings within ±10°, and track a selected course, radial, or bearing within ¾-scale deflection of the course deviation indicator (CDI).',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Maintain Parameters (Hold)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.S5',
    description:
      'Comply with the holding pattern leg length and other restrictions, if applicable, associated with the holding pattern.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Comply Holding Restrictions',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.S6',
    description:
      'Use proper wind correction procedures to maintain the desired pattern and to arrive over the fix as close as possible to a specified time.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Apply Wind Correction (Hold)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.S7',
    description:
      'Use a multi-function display (MFD) and other graphical navigation displays, if installed, to monitor position in relation to the desired flightpath during holding.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Use MFD for Holding',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.S8',
    description:
      'Comply with ATC reporting requirements and restrictions associated with the holding pattern.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Comply ATC Reporting (Hold)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.III.B.S9',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Air Traffic Control (ATC) Clearances and Procedures',
    task: 'Holding Procedures',
    subTask: 'Apply SRM/CRM (Hold)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.A.K1',
    description:
      'Elements related to attitude instrument flying during straight-and-level flight, climbs, turns, and descents while conducting various instrument flight procedures.',
    area: 'Flight by Reference to Instruments',
    task: 'Instrument Flight',
    subTask: 'Attitude Instrument Flying',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.A.K2',
    description:
      'Interpretation, operation, and limitations of pitch, bank, and power instruments.',
    area: 'Flight by Reference to Instruments',
    task: 'Instrument Flight',
    subTask: 'Instrument Interpretation/Limits',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.A.K3',
    description: 'Normal and abnormal instrument indications and operations.',
    area: 'Flight by Reference to Instruments',
    task: 'Instrument Flight',
    subTask: 'Normal/Abnormal Indications',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.A.R1',
    description: 'Situations that can affect physiology and degrade instrument cross-check.',
    area: 'Flight by Reference to Instruments',
    task: 'Instrument Flight',
    subTask: 'Physiology/Cross-check Risk',
    knowledge: 'Aeromedical',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.A.R2',
    description: 'Spatial disorientation and optical illusions.',
    area: 'Flight by Reference to Instruments',
    task: 'Instrument Flight',
    subTask: 'Spatial Disorientation Risk',
    knowledge: 'Aeromedical',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.A.R3',
    description:
      'Flying unfamiliar helicopter or operating with unfamiliar flight display systems and avionics.',
    area: 'Flight by Reference to Instruments',
    task: 'Instrument Flight',
    subTask: 'Unfamiliar Equipment Risk (IMC)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.A.S1',
    description:
      'Maintain altitude ±100 feet during level flight, selected headings ±10°, airspeed ±10 knots, and bank angles ±5° during turns.',
    area: 'Flight by Reference to Instruments',
    task: 'Instrument Flight',
    subTask: 'Maintain Parameters (Basic IF)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.A.S2',
    description:
      'Use proper instrument cross-check and interpretation, and apply the appropriate pitch, bank, power, and trim corrections when applicable.',
    area: 'Flight by Reference to Instruments',
    task: 'Instrument Flight',
    subTask: 'Perform Instrument Scan/Control',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.K1',
    description:
      'Prevention of unusual attitudes, including flight causal, physiological, and environmental factors, and system and equipment failures.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Unusual Attitude Prevention',
    knowledge: 'Aeromedical',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.K2',
    description: 'Procedures for recovery from unusual attitudes in flight.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Unusual Attitude Recovery Proc',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.K3',
    description:
      'Procedures available to safely regain visual meteorological conditions (VMC) after flight into inadvertent instrument meteorological conditions or unintended instrument meteorological conditions (IIMC)/(UIMC).',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'IIMC/UIMC Recovery Proc',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.K4',
    description: 'Appropriate use of automation, if applicable.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Automation Use (UA)',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.R1',
    description:
      'Situations that could lead to loss of control in-flight (LOC-I) or unusual attitudes in-flight (e.g., stress, task saturation, inadequate instrument scan distractions, and spatial disorientation).',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'LOC-I/UA Causes Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.R2',
    description: 'Assessment of the unusual attitude.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'UA Assessment Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.R3',
    description: 'Control input errors inducing undesired aircraft attitudes, e.g. low G rotor.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Control Input Error Risk (UA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.R4',
    description: 'Pilot responses that lead to mast bumping in a low G condition, if applicable.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Mast Bumping Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.R5',
    description: 'Collision hazards.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Collision Risk (UA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.R6',
    description:
      'Distractions, task prioritization, loss of situational awareness, or disorientation.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Distraction/SA Loss Risk (UA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.R7',
    description: 'Interpreting flight instruments.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Instrument Interpretation Risk (UA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.R8',
    description: 'Control application solely by reference to instruments.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Instrument Control App Risk (UA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.R9',
    description: 'Operating envelope considerations.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Operating Envelope Risk (UA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.S1',
    description:
      'Use proper instrument cross-check and interpretation to identify an unusual attitude (including both nose-high and nose-low), and apply the appropriate pitch, bank, and power corrections, in the correct sequence, to return to a stabilized level flight attitude.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Perform UA Recovery',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.IV.B.S2',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Flight by Reference to Instruments',
    task: 'Recovery from Unusual Flight Attitudes',
    subTask: 'Apply SRM/CRM (UA)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.K1',
    description:
      'Ground-based navigation (orientation, course determination, equipment, tests, and regulations), including procedures for intercepting and tracking courses and arcs.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Ground-Based Nav/Intercept',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.K2',
    description:
      'Satellite-based navigation (orientation, course determination, equipment, tests, regulations, interference, appropriate use of databases, Receiver Autonomous Integrity Monitoring (RAIM), and Wide Area Augmentation System (WAAS)), including procedures for intercepting and tracking courses and arcs.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Satellite-Based Nav/Intercept',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.R1',
    description: 'Management of automated navigation and autoflight systems.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Autonav/Autoflight Mgmt Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.R2',
    description:
      'Distractions, task prioritization, loss of situational awareness, or disorientation.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Distraction/SA Loss Risk (Nav)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.R3',
    description: 'Limitations of the navigation system in use.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Nav System Limits Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S1',
    description:
      'Tune and identify the navigation facility/program the navigation system and verify system accuracy as appropriate for the equipment installed in the helicopter.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Tune/Identify/Verify Nav Equip',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S2',
    description: 'Determine aircraft position relative to the navigational facility or waypoint.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Determine Position',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S3',
    description: 'Set and orient to the course to be intercepted.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Set/Orient for Intercept',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S4',
    description:
      'Intercept the specified course at appropriate angle, inbound to or outbound from a navigational facility or waypoint.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Intercept Course',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S5',
    description: 'Maintain airspeed ±10 knots, altitude ±100 feet, and selected headings ±5°.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Maintain Parameters (Nav)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S6',
    description:
      'Apply proper correction to maintain a course, allowing no more than ¾-scale deflection of the course deviation indicator (CDI). If a distance measuring equipment (DME) arc is selected, maintain that arc ±1 nautical mile.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Maintain Course/Track/DME Arc',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S7',
    description:
      'Recognize navigational system or facility failure, and when required, report the failure to air traffic control (ATC).',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Recognize/Report Nav Failure',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S8',
    description:
      'Use a multi-function display (MFD) and other graphical navigation displays, if installed, to monitor position, track wind drift, and to maintain situational awareness.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Use MFD for Nav/SA',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S9',
    description:
      'At the discretion of the evaluator, use the autopilot to make appropriate course intercepts, if installed.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Use Autopilot for Intercept',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.A.S10',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Navigation Systems',
    task: 'Intercepting and Tracking Navigational Systems and DME Arcs',
    subTask: 'Apply SRM/CRM (Nav)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.K1',
    description:
      'Elements related to ATC routes, including departure procedures (DPs) and associated climb gradients; standard terminal arrival (STAR) procedures and associated constraints.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'DP/STAR Procedures',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.K2',
    description:
      'Pilot/controller responsibilities, communication procedures, and ATC services available to pilots.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Pilot/Controller Resp/Comms',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.R1',
    description: 'ATC communications and compliance with published procedures.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'ATC Comm/Compliance Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.R2',
    description: 'Limitations of traffic avoidance equipment.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Traffic Avoidance Equip Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.R3',
    description: 'Responsibility to use "see and avoid" techniques when possible.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'See and Avoid Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S1',
    description:
      'Select, identify (as necessary) and use the appropriate communication and navigation facilities associated with the proposed flight.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Select/Use Comm/Nav Facilities',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S2',
    description: 'Perform the appropriate checklist items relative to the phase of flight.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Perform Checklists (Dep/Enr/Arr)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S3',
    description: 'Use the current and appropriate paper or electronic navigation publications.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Use Current Nav Pubs (Dep/Enr/Arr)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S4',
    description:
      'Establish two-way communications with the proper controlling agency, use proper phraseology, and comply in a timely manner with all ATC instructions and airspace restrictions.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Establish Comm/Comply ATC',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S5',
    description:
      'Intercept all courses, radials, and bearings appropriate to the procedure, route, or clearance in a timely manner.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Intercept Courses (Dep/Enr/Arr)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S6',
    description: 'Comply with all applicable charted procedures.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Comply Charted Procedures',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S7',
    description:
      'Maintain airspeed ±10 knots, altitude ±100 feet, and selected headings ±10°, and apply proper correction to maintain a course allowing no more than ¾-scale deflection of the course deviation indicator (CDI).',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Maintain Parameters (Dep/Enr/Arr)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S8',
    description: 'Update/interpret weather in flight.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Update/Interpret Inflight Wx',
    knowledge: 'Weather',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S9',
    description:
      'Use displays of digital weather and aeronautical information, as applicable to maintain situational awareness.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Use Digital Wx/Info for SA',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.V.B.S10',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Navigation Systems',
    task: 'Departure, En Route, and Arrival Operations',
    subTask: 'Apply SRM/CRM (Dep/Enr/Arr)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.K1',
    description:
      'Procedures and limitations associated with a non-precision approach, including the differences between Localizer Performance (LP) and Lateral Navigation (LNAV) approach guidance.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Non-Precision App Proc/Limits',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.K2',
    description:
      'Navigation system indications and annunciations expected during an area navigation (RNAV) approach.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'RNAV App Indications',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.K3',
    description:
      'Ground-based and satellite-based navigation systems used for a non-precision approach.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Nav Systems (Non-Precision)',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.K4',
    description: 'A stabilized approach, including energy management concepts.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Stabilized Approach Concepts',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.K5',
    description: 'Copter Point-in-Space (PinS) approaches.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Copter PinS Approaches',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.R1',
    description: 'Deviating from the assigned approach procedure.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Approach Deviation Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.R2',
    description: 'Selecting a navigation frequency.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Nav Frequency Selection Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.R3',
    description: 'Management of automated navigation and autoflight systems.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Autonav/Autoflight Mgmt Risk (App)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.R4',
    description: 'Helicopter configuration during an approach and missed approach.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Config Risk (App/MA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.R5',
    description: 'An unstable approach, including excessive descent rates.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Unstable Approach Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.R6',
    description: 'Deteriorating weather conditions on approach.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Deteriorating Wx Risk (App)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.R7',
    description:
      'Operating below the minimum descent altitude (MDA) without proper visual references.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Below MDA Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S1',
    description: 'Accomplish the non-precision instrument approaches selected by the evaluator.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Perform Non-Precision App',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S2',
    description:
      'Establish two-way communications with air traffic control (ATC) appropriate for the phase of flight or approach segment, and use proper communication phraseology.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Establish Comm (App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S3',
    description:
      'Select, tune, identify, and confirm the operational status of navigation equipment to be used for the approach.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Set Up Nav Equip (App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S4',
    description: 'Comply with all clearances issued by ATC or the evaluator.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Comply Clearances (App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S5',
    description:
      'Recognize if any flight instrumentation is inaccurate or inoperative, and take appropriate action.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Recognize Instrument Failure (App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S6',
    description: 'Advise ATC or the evaluator if unable to comply with a clearance.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Report Inability to Comply',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S7',
    description: 'Complete the appropriate checklist(s).',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Complete Checklists (App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S8',
    description:
      'Establish the appropriate helicopter configuration and airspeed considering meteorological and operating conditions.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Establish Config/Airspeed (App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S9',
    description:
      'Maintain altitude ±100 feet, selected heading ±10°, airspeed ±10 knots, no more than ¾ scale CDI deflection, and accurately track radials, courses, or bearings, prior to beginning the final approach segment.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Maintain Parameters (IAF-FAF)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S10',
    description:
      'Adjust the published MDA and visibility criteria for the aircraft approach category, as appropriate, for factors that include Notices of Air Missions (NOTAMs), inoperative aircraft or navigation equipment, or inoperative visual aids associated with the landing environment, etc.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Adjust MDA/Vis Criteria',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S11',
    description: 'Establish a stabilized descent to the appropriate altitude.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Establish Stabilized Descent',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S12',
    description:
      'For the final approach segment, maintain no more than ¾ scale CDI deflection, airspeed ±10 knots, and altitude, if applicable, above MDA +100/-0 feet to the Visual Descent Point (VDP) or missed approach point (MAP).',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Maintain Parameters (Final App Seg)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S13',
    description:
      'Assess if the required visual references are available, and either initiate the missed approach procedure or continue for landing.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Assess Visual Ref/Decide',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S14',
    description:
      'Use a multi-function display (MFD) and other graphical navigation displays, if installed, to monitor position, track wind drift, and to maintain situational awareness.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Use MFD for SA (App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.A.S15',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Instrument Approach Procedures',
    task: 'Non-precision Approach',
    subTask: 'Apply SRM/CRM (Non-Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.K1',
    description:
      'Procedures and limitations associated with a precision approach, including determining required descent rates and adjusting minimums in the case of inoperative equipment.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Precision App Proc/Limits',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.K2',
    description: 'Navigation system displays, annunciations, and modes of operation.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Nav System Displays (Prec App)',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.K3',
    description:
      'Ground-based and satellite-based navigation systems (orientation, course determination, equipment, tests and regulations, interference, appropriate use of navigation data, signal integrity).',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Nav Systems (Prec App)',
    knowledge: 'Navigation',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.K4',
    description: 'A stabilized approach, including energy management concepts.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Stabilized Approach Concepts (Prec)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.R1',
    description: 'Deviating from the assigned approach procedure.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Approach Deviation Risk (Prec)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.R2',
    description: 'Selecting a navigation frequency.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Nav Frequency Selection Risk (Prec)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.R3',
    description: 'Management of automated navigation and autoflight systems.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Autonav/Autoflight Mgmt Risk (Prec App)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.R4',
    description: 'Helicopter configuration during an approach and missed approach.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Config Risk (Prec App/MA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.R5',
    description: 'An unstable approach, including excessive descent rates.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Unstable Approach Risk (Prec)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.R6',
    description: 'Deteriorating weather conditions on approach.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Deteriorating Wx Risk (Prec App)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.R7',
    description:
      'Continuing to descend below the Decision Altitude (DA)/Decision Height (DH) when the required visual references are not visible.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Below DA/DH Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S1',
    description: 'Accomplish the precision instrument approach(es) selected by the evaluator.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Perform Precision App',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S2',
    description:
      'Establish two-way communications with air traffic control (ATC) appropriate for the phase of flight or approach segment, and use proper communication phraseology.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Establish Comm (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S3',
    description:
      'Select, tune, identify, and confirm the operational status of navigation equipment to be used for the approach.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Set Up Nav Equip (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S4',
    description: 'Comply with all clearances issued by ATC or the evaluator.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Comply Clearances (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S5',
    description:
      'Recognize if any flight instrumentation is inaccurate or inoperative, and take appropriate action.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Recognize Instrument Failure (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S6',
    description: 'Advise ATC or the evaluator if unable to comply with a clearance.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Report Inability to Comply (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S7',
    description: 'Complete the appropriate checklist(s).',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Complete Checklists (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S8',
    description:
      'Establish the appropriate helicopter configuration and airspeed considering meteorological and operating conditions.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Establish Config/Airspeed (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S9',
    description:
      'Maintain altitude ±100 feet, selected heading ±10°, airspeed ±10 knots, no more than ¾ scale CDI deflection, and accurately track radials, courses, or bearings, prior to beginning the final approach segment.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Maintain Parameters (Prec IAF-FAF)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S10',
    description:
      'Adjust the published DA/DH and visibility criteria for the aircraft approach category, as appropriate, to account for NOTAMs, inoperative helicopter or navigation equipment, or inoperative visual aids associated with the landing environment.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Adjust DA/DH/Vis Criteria',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S11',
    description:
      'Establish a predetermined rate of descent at the point where vertical guidance begins, which approximates that required for the helicopter to follow the vertical guidance.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Establish Descent Rate (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S12',
    description:
      'Maintain a stabilized final approach from the final approach fix (FAF) to DA/DH allowing no more than ¾-scale deflection of either the vertical or lateral guidance indications, and maintain the desired airspeed ±10 knots.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Maintain Stabilized Final (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S13',
    description:
      'Immediately initiate the missed approach procedure when at the DA/DH, and the required visual references for the runway are not unmistakably visible and identifiable.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Initiate Missed Approach (Prec)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S14',
    description:
      'Transition to a normal landing approach only when the helicopter is in a position from which a descent to a landing on the runway or suitable point not aligned with the final approach path can be made at a normal rate of descent using normal maneuvering.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Transition to Landing (Prec)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S15',
    description:
      'Maintain a stabilized visual flight path from the DA/DH to the runway aiming point or descend visually to a suitable touchdown point not aligned with the instrument runway final course, as directed by the evaluator.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Maintain Visual Path to Landing',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S16',
    description:
      'Use a multi-function display (MFD) and other graphical navigation displays, if installed, to monitor position, track wind drift, and to maintain situational awareness.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Use MFD for SA (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.B.S17',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Instrument Approach Procedures',
    task: 'Precision Approach',
    subTask: 'Apply SRM/CRM (Prec App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.K1',
    description:
      'Elements related to missed approach procedures and limitations associated with standard instrument approaches, including while using a flight management system (FMS) or autopilot, if equipped.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Missed Approach Proc/Limits',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.R1',
    description: 'Deviations from prescribed procedures or ATC instructions.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Procedure Deviation Risk (MA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.R2',
    description: 'Holding, diverting, or electing to fly the approach again.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Post-MA Decisions Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.R3',
    description: 'Helicopter configuration during an approach and missed approach.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Config Risk (App/MA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.R4',
    description:
      'Factors that might lead to executing a missed approach procedure before the MAP or to a go-around below DA, DH, or MDA, as applicable.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Early MA/Go-Around Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.R5',
    description: 'Management of automated navigation and autoflight systems.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Autonav/Autoflight Mgmt Risk (MA)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.S1',
    description: 'Promptly initiate the missed approach procedure and report it to ATC.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Initiate/Report Missed Approach',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.S2',
    description:
      'Apply the appropriate power setting and configure the helicopter to establish a positive rate of climb in accordance with the POH/RFM.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Establish Climb (MA)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.S3',
    description: 'Comply with the published or alternate missed approach procedure.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Comply Missed Approach Proc',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.S4',
    description:
      'Advise ATC or the evaluator if unable to comply with a clearance, restriction, or climb gradient.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Report Inability to Comply (MA)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.S5',
    description:
      'Follow the recommended checklist items appropriate to the missed approach/go-around procedure.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Follow Checklists (MA)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.S6',
    description:
      'Maintain the recommended airspeed ±10 knots; heading, course, or bearing ±10°; and altitude(s) ±100 feet during the missed approach procedure.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Maintain Parameters (MA)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.S7',
    description:
      'Use an MFD and other graphical navigation displays, if installed, to monitor position and track to help navigate the missed approach.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Use MFD for Nav (MA)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.S8',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Apply SRM/CRM (MA)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.C.S9',
    description:
      'Request ATC clearance to attempt another approach, proceed to the alternate airport, holding fix, or other clearance limit, as appropriate, or as directed by the evaluator.',
    area: 'Instrument Approach Procedures',
    task: 'Missed Approach',
    subTask: 'Request Further Clearance (MA)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.K1',
    description:
      "Elements related to the pilot's responsibilities, and the environmental, operational, and meteorological factors that affect landing from a straight-in approach.",
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Landing Factors/Responsibilities',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.K2',
    description: 'Airport signs, markings, and lighting, including approach lighting systems.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Airport Markings/Lighting',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.K3',
    description: 'Appropriate landing profiles and aircraft configurations.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Landing Profiles/Config',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.R1',
    description: 'Attempting to land from an unstable approach.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Unstable Approach Landing Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.R2',
    description: 'Flying below the glidepath.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Below Glidepath Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.R3',
    description: 'Transitioning from instrument to visual references for landing.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Inst-to-Visual Transition Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.R4',
    description: 'Aircraft configuration for landing.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Landing Config Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.S1',
    description:
      'Transition at the DA/DH, MDA, or visual descent point (VDP) to a visual flight condition, allowing for safe visual maneuvering and a normal landing.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Transition to Visual/Landing',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.S2',
    description:
      'Adhere to all ATC or evaluator advisories, such as NOTAMS, windshear, wake turbulence, runway surface, and other operational considerations.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Adhere to Advisories (Landing)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.S3',
    description: 'Complete the appropriate checklist(s).',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Complete Checklists (Landing)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.S4',
    description: 'Maintain positive helicopter control throughout the landing maneuver.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Maintain Control (Landing)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VI.D.S5',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Instrument Approach Procedures',
    task: 'Landing from an Instrument Approach',
    subTask: 'Apply SRM/CRM (Landing)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.A.K1',
    description:
      'Procedures to follow in the event of lost communication during various phases of flight, including techniques for reestablishing communications, when it is acceptable to deviate from an instrument flight rules (IFR) clearance, and when to begin an approach at the destination.',
    area: 'Emergency Operations',
    task: 'Loss of Communications',
    subTask: 'Lost Comms Procedures',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.A.R1',
    description: 'Possible reasons for loss of communication.',
    area: 'Emergency Operations',
    task: 'Loss of Communications',
    subTask: 'Lost Comms Causes Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.A.R2',
    description: 'Deviation from procedures for lost communications.',
    area: 'Emergency Operations',
    task: 'Loss of Communications',
    subTask: 'Lost Comms Deviation Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.A.S1',
    description: 'Recognize a simulated loss of communication.',
    area: 'Emergency Operations',
    task: 'Loss of Communications',
    subTask: 'Recognize Lost Comms',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.A.S2',
    description: 'Simulate actions to re-establish communication.',
    area: 'Emergency Operations',
    task: 'Loss of Communications',
    subTask: 'Re-establish Comm Actions',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.A.S3',
    description: 'Determine whether to continue to flight plan destination or deviate.',
    area: 'Emergency Operations',
    task: 'Loss of Communications',
    subTask: 'Lost Comms Decision (Route)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.A.S4',
    description: 'Determine appropriate time to begin an approach.',
    area: 'Emergency Operations',
    task: 'Loss of Communications',
    subTask: 'Lost Comms Decision (Approach)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.A.S5',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Emergency Operations',
    task: 'Loss of Communications',
    subTask: 'Apply SRM/CRM (Lost Comms)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.K1',
    description: 'Instrument approach procedures with one engine inoperative.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'OEI Approach Procedures',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.R1',
    description: 'Potential engine failure during approach and landing.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Engine Failure Risk (App/Ldg)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.R2',
    description: 'Aircraft/powerplant limitations.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Acft/Powerplant Limits Risk (OEI)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.R3',
    description:
      'Distractions, task prioritization, loss of situational awareness, or disorientation.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Distraction/SA Loss Risk (OEI)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.R4',
    description: 'Collision hazards.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Collision Risk (OEI)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.R5',
    description: 'Configuring the helicopter.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Config Risk (OEI)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.R6',
    description: 'Performing a go-around/rejected landing with an engine failure.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'OEI Go-Around Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S1',
    description: 'Promptly recognize an engine failure and maintain positive helicopter control.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Recognize Eng Failure/Maintain Control',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S2',
    description:
      'Use flight controls and configure the helicopter as required to maintain best performance or as recommended by the manufacturer.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Configure for OEI Performance',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S3',
    description:
      "Follow the manufacturer's recommended emergency procedures and complete the appropriate checklist.",
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Follow OEI Emergency Proc/Checklist',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S4',
    description:
      'Maintain control and fly the helicopter within the one engine inoperative (OEI) operating limitations.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Fly within OEI Limits',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S5',
    description:
      'Monitor the operating engine and helicopter systems and make adjustments as necessary.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Monitor Systems (OEI)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S6',
    description:
      'Request and follow an actual or a simulated air traffic control (ATC) clearance for an instrument approach.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Request/Follow ATC (OEI App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S7',
    description: 'Maintain altitude ±100 feet, airspeed ±10 knots, and selected heading ±10°.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Maintain Parameters (OEI App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S8',
    description:
      'Establish a rate of descent that ensures arrival at the minimum descent altitude (MDA) or decision altitude (DA)/decision height (DH) with the helicopter in a position from which a descent to the intended runway or other landing point can be made.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Establish Descent (OEI App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S9',
    description:
      'On final approach segment, maintain vertical (as applicable) and lateral guidance within ¾-scale deflection.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Maintain Guidance (OEI Final)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S10',
    description: 'Execute a landing.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Execute Landing (OEI)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S11',
    description: 'Complete the appropriate checklist(s).',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Complete Checklists (OEI App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.B.S12',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Emergency Operations',
    task: 'Instrument Approach and Landing with an Inoperative Engine (Simulated) (Multiengine Helicopter Only)',
    subTask: 'Apply SRM/CRM (OEI App)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.C.K1',
    description:
      'Recognizing if primary flight instruments are inaccurate or inoperative, and advising ATC or the evaluator.',
    area: 'Emergency Operations',
    task: 'Approach with Loss of Primary Flight Instrument Indicators',
    subTask: 'Recognize Primary Inst Failure',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.C.K2',
    description:
      'Possible failure modes of primary instruments and how to correct or minimize the effect of the loss.',
    area: 'Emergency Operations',
    task: 'Approach with Loss of Primary Flight Instrument Indicators',
    subTask: 'Primary Inst Failure Modes',
    knowledge: 'Systems',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.C.R1',
    description: 'Use of secondary flight displays when primary displays have failed.',
    area: 'Emergency Operations',
    task: 'Approach with Loss of Primary Flight Instrument Indicators',
    subTask: 'Secondary Display Use Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.C.R2',
    description: 'Maintaining helicopter control.',
    area: 'Emergency Operations',
    task: 'Approach with Loss of Primary Flight Instrument Indicators',
    subTask: 'Control Maintenance Risk (Partial Panel)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.C.R3',
    description:
      'Distractions, task prioritization, loss of situational awareness, or disorientation.',
    area: 'Emergency Operations',
    task: 'Approach with Loss of Primary Flight Instrument Indicators',
    subTask: 'Distraction/SA Loss Risk (Partial Panel)',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.C.S1',
    description: 'Advise ATC or the evaluator if unable to comply with a clearance.',
    area: 'Emergency Operations',
    task: 'Approach with Loss of Primary Flight Instrument Indicators',
    subTask: 'Report Inability to Comply (Partial Panel)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.C.S2',
    description:
      'Complete a non-precision instrument approach without the use of the primary flight instruments using the skill elements of the non-precision approach Task (see Area of Operation VI, Task A).',
    area: 'Emergency Operations',
    task: 'Approach with Loss of Primary Flight Instrument Indicators',
    subTask: 'Perform Partial Panel Non-Prec App',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VII.C.S3',
    description:
      'Use single-pilot resource management (SRM) or crew resource management (CRM), as appropriate.',
    area: 'Emergency Operations',
    task: 'Approach with Loss of Primary Flight Instrument Indicators',
    subTask: 'Apply SRM/CRM (Partial Panel)',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VIII.A.K1',
    description: 'Procedures for documenting in-flight/postflight discrepancies.',
    area: 'Postflight Procedures',
    task: 'Checking Instruments and Equipment',
    subTask: 'Documenting Discrepancies',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
  {
    id: 'IH.VIII.A.R1',
    description:
      'Performance and documentation of postflight inspection and helicopter discrepancies.',
    area: 'Postflight Procedures',
    task: 'Checking Instruments and Equipment',
    subTask: 'Postflight Inspection/Doc Risk',
    knowledge: 'Risk Management',
    examType: 'IRH',
  },
  {
    id: 'IH.VIII.A.S1',
    description:
      'Conduct a postflight inspection and document discrepancies and servicing requirements, if any.',
    area: 'Postflight Procedures',
    task: 'Checking Instruments and Equipment',
    subTask: 'Perform Postflight Inspection',
    knowledge: 'Procedures',
    examType: 'IRH',
  },
];
