export const AcsCodes = [
  {
    id: 'MC.I.A.K1',
    description: 'Currency and recordkeeping.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Pilot Qualifications and Responsibilities',
    subTask: 'Currency/Recordkeeping',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.A.K2',
    description:
      'Documents required to exercise commercial pilot privileges, as per 14 CFR part 61.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Pilot Qualifications and Responsibilities',
    subTask: 'Required Documents',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.A.K3',
    description:
      'Passenger briefing requirements, to include operation and required use of safety restraint systems.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Pilot Qualifications and Responsibilities',
    subTask: 'Passenger Briefing',
    knowledge: 'Procedures',
    examType: 'MCN',
  },
  {
    id: 'MC.I.A.K4',
    description: 'Responsibility of the PIC, as per 14 CFR part 91, subparts A-E.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Pilot Qualifications and Responsibilities',
    subTask: 'PIC Responsibility',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.A.K5',
    description:
      'Regulatory requirements for supplemental oxygen use by flight crew and passengers.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Pilot Qualifications and Responsibilities',
    subTask: 'Supplemental Oxygen',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.B.K1a',
    description: 'Certificate location and expiration dates',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Airworthiness Requirements',
    subTask: 'Aircraft Certificates',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.B.K1b',
    description: 'Required inspections and aircraft logbook documentation',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Airworthiness Requirements',
    subTask: 'Inspections/Logbooks',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.B.K1c',
    description: 'Airworthiness Directives and Special Airworthiness Information Bulletins',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Airworthiness Requirements',
    subTask: 'ADs/SAIBs',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.B.K1d',
    description: 'Aircraft Flight Manual/POH, markings, and placards',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Airworthiness Requirements',
    subTask: 'AFM/POH/Placards',
    knowledge: 'Aircraft Systems',
    examType: 'MCN',
  },
  {
    id: 'MC.I.B.K2',
    description: 'Pilot-performed preventive maintenance.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Airworthiness Requirements',
    subTask: 'Preventive Maintenance',
    knowledge: 'Maintenance',
    examType: 'MCN',
  },
  {
    id: 'MC.I.B.K3a',
    description: 'Flying with inoperative equipment',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Airworthiness Requirements',
    subTask: 'Inoperative Equipment',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.B.K3b',
    description: 'Using an approved Minimum Equipment List (MEL)',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Airworthiness Requirements',
    subTask: 'MEL Usage',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.B.K3c',
    description: 'Required discrepancy records or placards',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Airworthiness Requirements',
    subTask: 'Discrepancy Records',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.B.K4',
    description:
      'Emergency Locator Transmitter (ELT) operations, limitations, and testing requirements.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Airworthiness Requirements',
    subTask: 'ELT Operations',
    knowledge: 'Aircraft Systems',
    examType: 'MCN',
  },
  {
    id: 'MC.I.C.K1',
    description: 'Medical certificates, classes, and validity time period.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Medical Certification and Qualification',
    subTask: 'Medical Certificates',
    knowledge: 'Aeromedical',
    examType: 'MCN',
  },
  {
    id: 'MC.I.C.K2',
    description: 'Inspection of medical certificates.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Medical Certification and Qualification',
    subTask: 'Medical Inspection',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.C.K3',
    description: 'Medical certificates and exercising pilot certificate privileges.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Medical Certification and Qualification',
    subTask: 'Medical Privileges',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.I.C.K4',
    description: 'Use of U.S. Armed Forces Medical Examination.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Medical Certification and Qualification',
    subTask: 'Military Medical',
    knowledge: 'Aeromedical',
    examType: 'MCN',
  },
  {
    id: 'MC.I.C.K5',
    description: 'BasicMed and exercising Commercial Pilot privileges.',
    area: 'Commercial Pilot Privileges and Limitations',
    task: 'Medical Certification and Qualification',
    subTask: 'BasicMed',
    knowledge: 'Aeromedical',
    examType: 'MCN',
  },
  {
    id: 'MC.II.A.K1',
    description: 'Types of airspace/airspace classes and associated requirements and limitations.',
    area: 'Air Traffic',
    task: 'National Airspace System',
    subTask: 'Airspace Classes',
    knowledge: 'Airspace',
    examType: 'MCN',
  },
  {
    id: 'MC.II.A.K2',
    description: 'Charting symbology.',
    area: 'Air Traffic',
    task: 'National Airspace System',
    subTask: 'Charting Symbology',
    knowledge: 'Navigation',
    examType: 'MCN',
  },
  {
    id: 'MC.II.A.K3',
    description:
      'Special use airspace (SUA), special flight rules areas (SFRA), temporary flight restrictions (TFR), and other airspace areas.',
    area: 'Air Traffic',
    task: 'National Airspace System',
    subTask: 'Special Use Airspace',
    knowledge: 'Airspace',
    examType: 'MCN',
  },
  {
    id: 'MC.II.A.K4',
    description: 'Altitude selection accounting for terrain and obstacles, VFR cruising altitudes.',
    area: 'Air Traffic',
    task: 'National Airspace System',
    subTask: 'Altitude Selection',
    knowledge: 'Navigation',
    examType: 'MCN',
  },
  {
    id: 'MC.II.A.K5',
    description: 'Compliance with ATC clearances and instructions.',
    area: 'Air Traffic',
    task: 'National Airspace System',
    subTask: 'ATC Compliance',
    knowledge: 'ATC Procedures',
    examType: 'MCN',
  },
  {
    id: 'MC.II.A.K6',
    description: 'Airport operations.',
    area: 'Air Traffic',
    task: 'National Airspace System',
    subTask: 'Airport Operations',
    knowledge: 'Procedures',
    examType: 'MCN',
  },
  {
    id: 'MC.II.A.K7',
    description: 'Right-of-way rules.',
    area: 'Air Traffic',
    task: 'National Airspace System',
    subTask: 'Right-of-Way',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
  {
    id: 'MC.III.A.K1',
    description: 'National Transportation Safety Board (NTSB) accident/incident reporting.',
    area: 'Accident Reporting',
    task: 'Accident Reporting',
    subTask: 'NTSB Reporting',
    knowledge: 'Regulations',
    examType: 'MCN',
  },
];
