export const AcsCodes = [
  {
    id: 'UA.I.A.K1',
    description: 'Applicability of 14 CFR part 107 to small unmanned aircraft operations.',
    area: 'Regulations',
    task: 'General',
    subTask: 'Applicability',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.A.K2',
    description: 'Definitions used in 14 CFR part 107.',
    area: 'Regulations',
    task: 'General',
    subTask: 'Definitions',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.A.K3',
    description:
      'The ramifications of falsification, reproduction, or alteration of a certificate, rating, authorization, record, or report.',
    area: 'Regulations',
    task: 'General',
    subTask: 'Falsification Consequences',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.A.K4',
    description: 'Accident reporting.',
    area: 'Regulations',
    task: 'General',
    subTask: 'Accident Reporting',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.A.K5',
    description: 'Inspection, testing, and demonstration of compliance.',
    area: 'Regulations',
    task: 'General',
    subTask: 'Compliance Demonstration',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.A.K6',
    description: 'Multiple category sUAS.',
    area: 'Regulations',
    task: 'General',
    subTask: 'sUAS Categories',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.A.K7',
    description: 'Record retention.',
    area: 'Regulations',
    task: 'General',
    subTask: 'Record Retention',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.A.K8',
    description: 'Previously manufactured sUAS.',
    area: 'Regulations',
    task: 'General',
    subTask: 'Legacy sUAS',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K1',
    description: 'Registration requirements for sUAS.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Registration',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K2',
    description: 'Requirement for the sUAS to be in a condition for safe operation.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Condition for Safe Operation',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K3',
    description: 'Medical condition(s) that would interfere with safe operation of an sUAS.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Medical Fitness',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K4',
    description: 'Responsibility and authority of the remote PIC.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'PIC Authority',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K4a',
    description: 'a. Allowing a person other than the remote PIC to manipulate the flight controls',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Control Delegation',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K5',
    description: 'Regulatory deviation and reporting requirements for in-flight emergencies.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Emergency Deviation Reporting',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K6',
    description: 'Hazardous operations.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Hazardous Operations',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K6a',
    description: 'a. Careless or reckless',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Careless/Reckless Operation',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K6b',
    description: 'b. Dropping an object',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Dropping Objects',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K7',
    description: 'Operating from a moving aircraft or moving land- or water-borne vehicle.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Operating from Moving Vehicles',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K8',
    description: 'Alcohol or drugs and the provisions on prohibition of use.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Alcohol/Drug Prohibition',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K9',
    description: 'Daylight operations.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Daylight Operations',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K10',
    description: 'Visual line of sight (VLOS) aircraft operations.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'VLOS Operations',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K11',
    description: 'Requirements when a visual observer is used.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Visual Observer Use',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K12',
    description: 'Prohibition of operating multiple sUAS.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Multiple sUAS Operations',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K13',
    description: 'Prohibition of carrying hazardous material.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Hazardous Material Carriage',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K14',
    description: 'Staying safely away from other aircraft and right-of-way rules.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Right-of-Way Rules',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K14a',
    description:
      'a. See and avoid other aircraft and other potential hazard considerations of the remote PIC',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'See and Avoid',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K15',
    description: 'Operations over human beings (Refer to Area of Operation I, Task E).',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Operations Over People',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K16',
    description: 'Prior authorization required for operation in certain airspace.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Airspace Authorization',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K17',
    description: 'Operating in the vicinity of airports.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Airport Vicinity Operations',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K18',
    description: 'Operating in prohibited or restricted areas.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Prohibited/Restricted Areas',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K19',
    description:
      'Flight restrictions in the proximity of certain areas designated by notice to airmen (NOTAM).',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'NOTAM Restrictions',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K20',
    description: 'Preflight familiarization, inspection, and actions for aircraft operations.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Preflight Actions',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K21',
    description: 'Operating limitations for sUAS.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Operating Limitations',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K21a',
    description: 'a. Maximum groundspeed',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Groundspeed Limit',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K21b',
    description: 'b. Altitude limitations',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Altitude Limits',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K21c',
    description: 'c. Minimum visibility',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Visibility Minimums',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K21d',
    description: 'd. Cloud clearance requirements',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Cloud Clearance',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K22',
    description: 'Requirements for a Remote Pilot Certificate with an sUAS rating.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Certification Requirements',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K23',
    description: 'Automated operations.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Automated Operations',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K24',
    description: 'Civil twilight operations.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Twilight Operations',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K25',
    description: 'Night operations.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Night Operations',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K26',
    description: 'Transportation of property.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Property Transportation',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K27',
    description: 'ATC transponder equipment prohibition.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'Transponder Prohibition',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.B.K28',
    description: 'ADS-B Out prohibition.',
    area: 'Regulations',
    task: 'Operating Rules',
    subTask: 'ADS-B Out Prohibition',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.C.K1',
    description: 'Offenses involving alcohol or drugs.',
    area: 'Regulations',
    task: 'Remote Pilot Certification with an sUAS Rating',
    subTask: 'Alcohol/Drug Offenses',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.C.K2',
    description:
      'The consequences of refusing to submit to a drug or alcohol test or to furnish test results.',
    area: 'Regulations',
    task: 'Remote Pilot Certification with an sUAS Rating',
    subTask: 'Test Refusal Consequences',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.C.K3',
    description: 'The eligibility requirements for a Remote Pilot Certificate with an SUAS rating.',
    area: 'Regulations',
    task: 'Remote Pilot Certification with an sUAS Rating',
    subTask: 'Eligibility Requirements',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.C.K4',
    description: 'Aeronautical knowledge recency.',
    area: 'Regulations',
    task: 'Remote Pilot Certification with an sUAS Rating',
    subTask: 'Knowledge Recency',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.D.K1',
    description: 'Waiver policy and requirements.',
    area: 'Regulations',
    task: 'Waivers',
    subTask: 'Waiver Policy',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K1',
    description: 'Remote pilot responsibilities when operating over people.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'PIC Responsibilities (OOP)',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K2',
    description: 'Operations over people at night.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Night OOP',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K3',
    description: 'Category of operations, including:',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'OOP Categories',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K3a',
    description: 'a. Category 1',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Category 1 OOP',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K3b',
    description: 'b. Category 2',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Category 2 OOP',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K3c',
    description: 'c. Category 3',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Category 3 OOP',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K3d',
    description: 'd. Category 4',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Category 4 OOP',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K4',
    description: 'Selecting an operational area.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Operational Area Selection',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K5',
    description: 'Minimum distances from a person.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Minimum Distances (OOP)',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K6',
    description: 'Operations over moving vehicles.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Operations Over Moving Vehicles',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K7',
    description: 'Modifications to an sUAS.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'sUAS Modifications (OOP)',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K8',
    description: 'Closed and restricted access sites.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Closed/Restricted Sites (OOP)',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K9',
    description: 'Remote Pilot operating instructions.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Operating Instructions (OOP)',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K10',
    description: 'Required components and Category declaration.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Components/Declaration (OOP)',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K11',
    description: 'Optional components.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Optional Components (OOP)',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K12',
    description: 'Applicant produced, designed, or modified SUAS for operations over people.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Self-Modified sUAS (OOP)',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K13',
    description: 'Declaration of Compliance (DoC).',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Declaration of Compliance',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K14',
    description: 'Maintenance of an sUAS that is eligible for operations over people.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Maintenance (OOP)',
    knowledge: 'Maintenance',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K15',
    description: 'Means of Compliance (MoC).',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Means of Compliance',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K16',
    description: 'Impact kinetic energy.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Kinetic Energy (OOP)',
    knowledge: 'Physics',
    examType: 'UAG',
  },
  {
    id: 'UA.I.E.K17',
    description: 'Exposed rotating parts.',
    area: 'Regulations',
    task: 'Operations Over People',
    subTask: 'Exposed Rotating Parts',
    knowledge: 'Safety',
    examType: 'UAG',
  },
  {
    id: 'UA.I.F.K1',
    description: 'Standard remote identification.',
    area: 'Regulations',
    task: 'Remote Identification (RID)',
    subTask: 'Standard RID',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.F.K2',
    description: 'Alternative remote identification.',
    area: 'Regulations',
    task: 'Remote Identification (RID)',
    subTask: 'Alternative RID',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.F.K3',
    description: 'Operations for aeronautical research.',
    area: 'Regulations',
    task: 'Remote Identification (RID)',
    subTask: 'Research Operations (RID)',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.F.K4',
    description: 'ADS-B Out.',
    area: 'Regulations',
    task: 'Remote Identification (RID)',
    subTask: 'ADS-B Out (RID Context)',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.I.F.K5',
    description: 'Confirmation of identification.',
    area: 'Regulations',
    task: 'Remote Identification (RID)',
    subTask: 'Identification Confirmation (RID)',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.I.F.K6',
    description: 'Minimum message elements broadcast for remote identification.',
    area: 'Regulations',
    task: 'Remote Identification (RID)',
    subTask: 'RID Message Elements',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.I.F.K7',
    description: 'Product labeling.',
    area: 'Regulations',
    task: 'Remote Identification (RID)',
    subTask: 'Product Labeling (RID)',
    knowledge: 'Regulations',
    examType: 'UAG',
  },
  {
    id: 'UA.II.A.K1',
    description: 'General airspace:',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Classification',
    subTask: 'Airspace Classification',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.A.K1a',
    description: 'a. Class B controlled airspace',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Classification',
    subTask: 'Class B Airspace',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.A.K1b',
    description: 'b. Class C controlled airspace',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Classification',
    subTask: 'Class C Airspace',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.A.K1c',
    description: 'c. Class D controlled airspace',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Classification',
    subTask: 'Class D Airspace',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.A.K1d',
    description: 'd. Class E controlled airspace',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Classification',
    subTask: 'Class E Airspace',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.A.K1e',
    description: 'e. Class G uncontrolled airspace',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Classification',
    subTask: 'Class G Airspace',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.A.K2',
    description:
      'Special-use airspace, such as prohibited, restricted, warning areas, military operation areas, alert areas, and controlled firing areas.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Classification',
    subTask: 'Special Use Airspace',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.A.K3',
    description:
      'Other airspace areas, such as Airport Advisory Services, Military Training Routes (MTRs), Temporary Flight Restrictions (TFRs), Parachute Jump Operations, Terminal Radar Service Areas (TRSAs), National Security Areas (NSA) and Visual Flight Rules (VFR) routes.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Classification',
    subTask: 'Other Airspace Areas',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.A.K4',
    description: 'Air Traffic Control (ATC) and the NAS.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Classification',
    subTask: 'ATC & NAS Overview',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K1',
    description: 'Basic weather minimums.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Weather Minimums',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K2',
    description: 'ATC authorizations and related operating limitations.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'ATC Authorizations/Limits',
    knowledge: 'Airspace',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K3',
    description: 'Operations near airports.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Airport Operations',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K4',
    description: 'Potential flight hazards.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Flight Hazards',
    knowledge: 'Safety',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K4a',
    description: 'a. Common aircraft accident causal factors',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Accident Causes',
    knowledge: 'Safety',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K4b',
    description: 'b. Avoid flight beneath unmanned balloons',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Balloon Avoidance',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K4c',
    description: 'c. Emergency airborne inspection of other aircraft',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Airborne Inspection',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K4d',
    description: 'd. Precipitation static',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Precipitation Static',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K4e',
    description:
      'e. Light amplification by stimulated emission of radiation (laser) operations and reporting illumination of aircraft',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Laser Operations/Reporting',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K4f',
    description:
      'f. Avoiding flight in the vicinity of thermal plumes such as smoke stacks and cooling towers',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Thermal Plume Avoidance',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K4g',
    description: 'g. Flying in the wire environment',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Wire Environment Flying',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K5',
    description:
      'The NOTAM system, including how to obtain an established NOTAM through Flight Service.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'NOTAM System',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K6',
    description: 'Operator equipment for night flight.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Night Flight Equipment',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K7',
    description: 'Ground structures and ground structure lighting.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Ground Structures/Lighting',
    knowledge: 'Safety',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K8',
    description: 'Hazards on the ground that do not have lighting.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Unlit Ground Hazards',
    knowledge: 'Safety',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K9',
    description: 'Manned aircraft lighting.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'Manned Aircraft Lighting',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.II.B.K10',
    description: 'sUAS lighting requirements.',
    area: 'Airspace Classification and Operating Requirements',
    task: 'Airspace Operational Requirements',
    subTask: 'sUAS Lighting',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.III.A.K1',
    description:
      'Internet weather briefing and sources of weather available for flight planning purposes.',
    area: 'Weather',
    task: 'Sources of Weather',
    subTask: 'Weather Sources/Briefing',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.A.K2',
    description: 'Aviation routine weather reports (METAR).',
    area: 'Weather',
    task: 'Sources of Weather',
    subTask: 'METAR',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.A.K3',
    description: 'Terminal aerodrome forecasts (TAF).',
    area: 'Weather',
    task: 'Sources of Weather',
    subTask: 'TAF',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.A.K4',
    description: 'Weather charts.',
    area: 'Weather',
    task: 'Sources of Weather',
    subTask: 'Weather Charts',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.A.K5',
    description:
      'Automated surface observing systems (ASOS) and automated weather observing systems (AWOS).',
    area: 'Weather',
    task: 'Sources of Weather',
    subTask: 'ASOS/AWOS',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1',
    description: 'Weather factors and their effects on performance.',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Weather Effects',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1a',
    description: 'a. Density altitude',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Density Altitude',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1b',
    description: 'b. Wind and currents',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Wind/Currents',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1c',
    description: 'c. Atmospheric stability, pressure, and temperature',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Stability/Pressure/Temp',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1d',
    description: 'd. Air masses and fronts',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Air Masses/Fronts',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1e',
    description: 'e. Thunderstorms and microbursts',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Thunderstorms/Microbursts',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1f',
    description: 'f. Tornadoes',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Tornadoes',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1g',
    description: 'g. Icing',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Icing',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1h',
    description: 'h. Hail',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Hail',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1i',
    description: 'i. Fog',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Fog',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1j',
    description: 'j. Ceiling and visibility',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Ceiling/Visibility',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.III.B.K1k',
    description: 'k. Lightning',
    area: 'Weather',
    task: 'Effects of Weather on Performance',
    subTask: 'Lightning',
    knowledge: 'Weather',
    examType: 'UAG',
  },
  {
    id: 'UA.IV.A.K1',
    description: 'General loading and performance, including:',
    area: 'Loading and Performance',
    task: 'Loading and Performance',
    subTask: 'Loading/Performance Intro',
    knowledge: 'Performance',
    examType: 'UAG',
  },
  {
    id: 'UA.IV.A.K1a',
    description: 'a. Effects of loading changes',
    area: 'Loading and Performance',
    task: 'Loading and Performance',
    subTask: 'Loading Change Effects',
    knowledge: 'Performance',
    examType: 'UAG',
  },
  {
    id: 'UA.IV.A.K1b',
    description: 'b. Balance, stability, and center of gravity',
    area: 'Loading and Performance',
    task: 'Loading and Performance',
    subTask: 'Balance/Stability/CG',
    knowledge: 'Performance',
    examType: 'UAG',
  },
  {
    id: 'UA.IV.A.K2',
    description:
      "Importance and use of performance data to calculate the effect on the aircraft's performance of an SUAS.",
    area: 'Loading and Performance',
    task: 'Loading and Performance',
    subTask: 'Performance Data Use',
    knowledge: 'Performance',
    examType: 'UAG',
  },
  {
    id: 'UA.V.A.K1',
    description: 'Airport operations with and without an operating control tower.',
    area: 'Operations',
    task: 'Radio Communications Procedures',
    subTask: 'Towered/Untowered Ops',
    knowledge: 'Communications',
    examType: 'UAG',
  },
  {
    id: 'UA.V.A.K2',
    description:
      'The description and use of a Common Traffic Advisory Frequency (CTAF) to monitor manned aircraft communications.',
    area: 'Operations',
    task: 'Radio Communications Procedures',
    subTask: 'CTAF Use',
    knowledge: 'Communications',
    examType: 'UAG',
  },
  {
    id: 'UA.V.A.K3',
    description:
      'Recommended traffic advisory procedures used by manned aircraft pilots such as self-announcing of position and intentions.',
    area: 'Operations',
    task: 'Radio Communications Procedures',
    subTask: 'Traffic Advisories',
    knowledge: 'Communications',
    examType: 'UAG',
  },
  {
    id: 'UA.V.A.K4',
    description:
      'Aeronautical advisory communication station (UNICOM) and associated communication procedures used by manned aircraft pilots.',
    area: 'Operations',
    task: 'Radio Communications Procedures',
    subTask: 'UNICOM Use',
    knowledge: 'Communications',
    examType: 'UAG',
  },
  {
    id: 'UA.V.A.K5',
    description: 'Automatic Terminal Information Service (ATIS).',
    area: 'Operations',
    task: 'Radio Communications Procedures',
    subTask: 'ATIS',
    knowledge: 'Communications',
    examType: 'UAG',
  },
  {
    id: 'UA.V.A.K6',
    description: 'Aircraft call signs and registration numbers.',
    area: 'Operations',
    task: 'Radio Communications Procedures',
    subTask: 'Call Signs/Registration',
    knowledge: 'Communications',
    examType: 'UAG',
  },
  {
    id: 'UA.V.A.K7',
    description: 'The phonetic alphabet.',
    area: 'Operations',
    task: 'Radio Communications Procedures',
    subTask: 'Phonetic Alphabet',
    knowledge: 'Communications',
    examType: 'UAG',
  },
  {
    id: 'UA.V.A.K8',
    description: 'Phraseology: altitudes, directions, speed, and time.',
    area: 'Operations',
    task: 'Radio Communications Procedures',
    subTask: 'Radio Phraseology',
    knowledge: 'Communications',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K1',
    description:
      'Types of airports such as towered, uncontrolled towered, heliport, and seaplane bases.',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'Airport Types',
    knowledge: 'Airports',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K2',
    description:
      'ATC towers, such as ensuring the remote pilot can monitor and interpret ATC communications to improve situational awareness.',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'ATC Tower Monitoring',
    knowledge: 'Airports',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K3',
    description: 'Runway markings and signage.',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'Runway Markings/Signs',
    knowledge: 'Airports',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K4',
    description: 'Traffic patterns used by manned aircraft pilots.',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'Traffic Patterns',
    knowledge: 'Airports',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K5',
    description: 'Security Identification Display Areas (SIDA).',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'SIDA',
    knowledge: 'Airports',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K6',
    description: 'Sources for airport data.',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'Airport Data Sources',
    knowledge: 'Airports',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K6a',
    description: 'a. Aeronautical charts',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'Aeronautical Charts',
    knowledge: 'Navigation',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K6b',
    description: 'b. Chart Supplements',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'Chart Supplements',
    knowledge: 'Navigation',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K7',
    description:
      'Avoiding bird and wildlife hazards and reporting collisions between aircraft and wildlife.',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'Bird/Wildlife Hazards',
    knowledge: 'Safety',
    examType: 'UAG',
  },
  {
    id: 'UA.V.B.K8',
    description: 'Airport and seaplane base lighting.',
    area: 'Operations',
    task: 'Airport Operations',
    subTask: 'Airport Lighting',
    knowledge: 'Airports',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K1',
    description: 'Emergency planning and communication.',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'Emergency Planning',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K2',
    description: 'Characteristics and potential hazards of lithium batteries.',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'Lithium Battery Hazards',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K2a',
    description: 'a. Safe transportation such as proper inspection and handling',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'Battery Transport/Handling',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K2b',
    description: 'b. Safe charging',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'Battery Charging',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K2c',
    description: 'c. Safe usage',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'Battery Usage',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K2d',
    description: 'd. Risks of fires involving lithium batteries',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'Battery Fire Risks',
    knowledge: 'Safety',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K3',
    description: 'Loss of aircraft control link and fly-aways.',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'Lost Link/Fly-aways',
    knowledge: 'Emergencies',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K4',
    description:
      'Loss of Global Positioning System (GPS) signal during flight and potential consequences.',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'GPS Loss Consequences',
    knowledge: 'Emergencies',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K5',
    description: 'Frequency spectrums and associated limitations.',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'Frequency Spectrum Limits',
    knowledge: 'Systems',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K6',
    description: 'Procedures for operations over people.',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'OOP Procedures',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.V.C.K7',
    description: 'Procedures for operations at night.',
    area: 'Operations',
    task: 'Emergency Procedures',
    subTask: 'Night Operations Procedures',
    knowledge: 'Procedures',
    examType: 'UAG',
  },
  {
    id: 'UA.V.D.K1',
    description: 'Aeronautical decision-making (ADM).',
    area: 'Operations',
    task: 'Aeronautical Decision-Making',
    subTask: 'ADM Principles',
    knowledge: 'ADM',
    examType: 'UAG',
  },
  {
    id: 'UA.V.D.K1a',
    description: 'a. Effective team communication',
    area: 'Operations',
    task: 'Aeronautical Decision-Making',
    subTask: 'Team Communication',
    knowledge: 'CRM',
    examType: 'UAG',
  },
  {
    id: 'UA.V.D.K1b',
    description: 'b. Task management',
    area: 'Operations',
    task: 'Aeronautical Decision-Making',
    subTask: 'Task Management',
    knowledge: 'CRM',
    examType: 'UAG',
  },
  {
    id: 'UA.V.D.K2',
    description: 'Crew Resource Management (CRM).',
    area: 'Operations',
    task: 'Aeronautical Decision-Making',
    subTask: 'CRM Principles',
    knowledge: 'CRM',
    examType: 'UAG',
  },
  {
    id: 'UA.V.D.K3',
    description: 'Situational awareness.',
    area: 'Operations',
    task: 'Aeronautical Decision-Making',
    subTask: 'Situational Awareness',
    knowledge: 'ADM',
    examType: 'UAG',
  },
  {
    id: 'UA.V.D.K4',
    description: 'Hazardous attitudes.',
    area: 'Operations',
    task: 'Aeronautical Decision-Making',
    subTask: 'Hazardous Attitudes',
    knowledge: 'ADM',
    examType: 'UAG',
  },
  {
    id: 'UA.V.D.K5',
    description: 'Hazard identification and risk assessment.',
    area: 'Operations',
    task: 'Aeronautical Decision-Making',
    subTask: 'Hazard/Risk Assessment',
    knowledge: 'ADM',
    examType: 'UAG',
  },
  {
    id: 'UA.V.E.K1',
    description:
      'Physiological considerations and their effects on safety such as dehydration and heatstroke.',
    area: 'Operations',
    task: 'Physiology',
    subTask: 'Dehydration/Heatstroke',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.V.E.K2',
    description: 'Drug and alcohol use.',
    area: 'Operations',
    task: 'Physiology',
    subTask: 'Drug/Alcohol Effects',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.V.E.K3',
    description: 'Prescription and over-the-counter medication.',
    area: 'Operations',
    task: 'Physiology',
    subTask: 'Medication Effects',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.V.E.K4',
    description: 'Hyperventilation.',
    area: 'Operations',
    task: 'Physiology',
    subTask: 'Hyperventilation',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.V.E.K5',
    description: 'Stress and fatigue.',
    area: 'Operations',
    task: 'Physiology',
    subTask: 'Stress/Fatigue',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.V.E.K6',
    description: 'Factors affecting vision.',
    area: 'Operations',
    task: 'Physiology',
    subTask: 'Vision Factors',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.V.E.K7',
    description: 'Fitness for flight.',
    area: 'Operations',
    task: 'Physiology',
    subTask: 'Fitness for Flight',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.V.E.K8',
    description: 'Physiological aspects of night operation.',
    area: 'Operations',
    task: 'Physiology',
    subTask: 'Night Vision Physiology',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.V.E.K9',
    description: 'Night illusions.',
    area: 'Operations',
    task: 'Physiology',
    subTask: 'Night Illusions',
    knowledge: 'Aeromedical',
    examType: 'UAG',
  },
  {
    id: 'UA.V.F.K1',
    description: 'Basic maintenance.',
    area: 'Operations',
    task: 'Maintenance and Inspection Procedures',
    subTask: 'Basic Maintenance',
    knowledge: 'Maintenance',
    examType: 'UAG',
  },
  {
    id: 'UA.V.F.K2',
    description: 'Preflight inspection.',
    area: 'Operations',
    task: 'Maintenance and Inspection Procedures',
    subTask: 'Preflight Inspection',
    knowledge: 'Maintenance',
    examType: 'UAG',
  },
  {
    id: 'UA.V.F.K3',
    description:
      'Techniques to mitigate mechanical failures of all elements used in SUAS operations such as the battery and any device(s) used to operate the sUAS.',
    area: 'Operations',
    task: 'Maintenance and Inspection Procedures',
    subTask: 'Failure Mitigation',
    knowledge: 'Maintenance',
    examType: 'UAG',
  },
  {
    id: 'UA.V.F.K4',
    description: 'Appropriate record keeping.',
    area: 'Operations',
    task: 'Maintenance and Inspection Procedures',
    subTask: 'Record Keeping',
    knowledge: 'Maintenance',
    examType: 'UAG',
  },
  {
    id: 'UA.V.F.K5',
    description: 'Persons that may perform maintenance on an sUAS.',
    area: 'Operations',
    task: 'Maintenance and Inspection Procedures',
    subTask: 'Maintenance Personnel',
    knowledge: 'Maintenance',
    examType: 'UAG',
  },
  {
    id: 'UA.V.F.K6',
    description: 'Preflight inspection for night operations.',
    area: 'Operations',
    task: 'Maintenance and Inspection Procedures',
    subTask: 'Night Preflight',
    knowledge: 'Maintenance',
    examType: 'UAG',
  },
  {
    id: 'UA.V.F.K7',
    description: "Manufacturer's Declaration of Compliance for Category 2 and 3 operations.",
    area: 'Operations',
    task: 'Maintenance and Inspection Procedures',
    subTask: 'Manufacturer DoC (Cat 2/3)',
    knowledge: 'Maintenance',
    examType: 'UAG',
  },
];
